name: "EnvTest"

on:
  workflow_dispatch:
    
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          TEST: 1
         # language=bash
        run: |
          run: echo '${{ toJSON(env) }}'
  
  
