name: "EnvTest"

on:
  workflow_dispatch:
    
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: null
        env:
          TEST: 1
         # language=bash
        run: |
          echo "$TEST"
  
  
